#include <stdio.h>
#include <stdlib.h>

int main(int argc, char **argv)
{
	if(argc != 3){
		printf("Required format: %s, op1, op2", argv[0]);
		return -1;
	}
	printf("segment .data\n");
	printf("\t_string_1 db\t\"Menú: [1] Resta. [2] Multiplicación. [3] Potencia 2 (número al cuadrado). [4] Salir.\", 0\n");
	printf("\t_string_2 db\t\"Su opción: \", 0\n");
	printf("\t_resta\tdb\t\" - \", 0\n");
	printf("\t_multiplicar\tdb\t\" * \", 0\n");
	printf("\t_igual\tdb\t\" = \", 0\n");
	printf("\n");
	printf("segment .bss\n");
	printf("\t__esp\tresd\t1\n");
	printf("\t_option\tresd\t1\n");
	printf("\t_operando_1\tresw\t1\n");
	printf("\t_operando_2 resw\t1\n");
	printf("\n");
	printf("segment .text\n");
	printf("\tglobal main\n");
	printf("\textern print_string, print_endofline, print_int\n");
	printf("\textern scan_int\n");
	printf("\n");
	printf("main:\n");
	printf("\tmov dword [__esp] , esp\n");
	printf("\n");
	printf("menu:\n");
	printf("\tpush dword _string_1\n");
	printf("\tcall print_string\n");
	printf("\tadd esp, 4\n");
	printf("\tcall print_endofline\n");
	printf("\t\n");
	printf("\tpush dword _string_2\n");
	printf("\tcall print_string\n");
	printf("\tadd esp, 4\n");
	printf("\n");
	printf("\tpush dword _option\n");
	printf("\tcall scan_int\n");
	printf("\tadd esp, 4\n");
	printf("\tpush dword [_option]\n");
	printf("\t\n");
	printf("\tpop eax\n");
	printf("\tcmp eax, 1\n");
	printf("\tje resta\n");
	printf("\tcmp eax, 2\n");
	printf("\tje multiplic\n");
	printf("\tcmp eax, 3\n");
	printf("\tje pot\n");
	printf("\tcmp eax, 4\n");
	printf("\tje quit\n");
	printf("\tcall menu\n");
	printf("\n");
	printf("resta:\n");
	printf("\n");
	printf("\tmov dword [_operando_1], %d\n", atoi(argv[1]));
	printf("\tpush dword [_operando_1]\n");
	printf("\tpop dword ebx\n");
	printf("\tpush dword [_operando_1]\n");
	printf("\tcall print_int\n");
	printf("\tadd esp, 4\n");
	printf("\n");
	printf("\tpush dword _resta\n");
	printf("\tcall print_string\n");
	printf("\tadd esp, 4\n");
	printf("\n");
	printf("\tmov dword [_operando_2], %d\n", atoi(argv[2]));
	printf("\tpush dword [_operando_2]\n");
	printf("\tpop dword ecx\n");
	printf("\tpush dword [_operando_2]\n");
	printf("\tcall print_int\n");
	printf("\tadd esp, 4\n");
	printf("\n");
	printf("\tpush dword _igual\n");
	printf("\tcall print_string\n");
	printf("\tadd esp, 4\n");
	printf("\n");
	printf("\tsub ebx, ecx\n");
	printf("\tpush dword ebx\n");
	printf("\tcall print_int\n");
	printf("\tadd esp, 4\n");
	printf("\tcall print_endofline\n");
	printf("\n");
	printf("\tcall menu\n");
	printf("\n");
	printf("multiplic:\n");
	printf("\tmov dword [_operando_1], %d\n", atoi(argv[1]));
	printf("\tpush dword [_operando_1]\n");
	printf("\tpop dword ebx\n");
	printf("\tpush dword [_operando_1]\n");
	printf("\tcall print_int\n");
	printf("\tadd esp, 4\n");
	printf("\n");
	printf("\tpush dword _multiplicar\n");
	printf("\tcall print_string\n");
	printf("\tadd esp, 4\n");
	printf("\n");
	printf("\tmov dword [_operando_2], %d\n", atoi(argv[2]));
	printf("\tpush dword [_operando_2]\n");
	printf("\tpop dword ecx\n");
	printf("\tpush dword [_operando_2]\n");
	printf("\tcall print_int\n");
	printf("\tadd esp, 4\n");
	printf("\n");
	printf("\tpush dword _igual\n");
	printf("\tcall print_string\n");
	printf("\tadd esp, 4\n");
	printf("\n");
	printf("\tmov eax, ebx\n");
	printf("\timul ecx\n");
	printf("\tpush dword eax\n");
	printf("\tcall print_int\n");
	printf("\tadd esp, 4\n");
	printf("\tcall print_endofline\n");
	printf("\tcall menu\n");
	printf("\n");
	printf("pot:\n");
	printf("\tmov dword [_operando_1], %d\n", atoi(argv[1]));
	printf("\tpush dword [_operando_1]\n");
	printf("\tpop dword ebx\n");
	printf("\tpush dword [_operando_1]\n");
	printf("\tcall print_int\n");
	printf("\tadd esp, 4\n");
	printf("\n");
	printf("\tpush dword _multiplicar\n");
	printf("\tcall print_string\n");
	printf("\tadd esp, 4\n");
	printf("\n");
	printf("\tmov dword [_operando_1], %d\n", atoi(argv[1]));
	printf("\tpush dword [_operando_1]\n");
	printf("\tcall print_int\n");
	printf("\tadd esp, 4\n");
	printf("\n");
	printf("\tpush dword _igual\n");
	printf("\tcall print_string\n");
	printf("\tadd esp, 4\n");
	printf("\n");
	printf("\tmov eax, ebx\n");
	printf("\timul ebx\n");
	printf("\tpush dword eax\n");
	printf("\tcall print_int\n");
	printf("\tadd esp, 4\n");
	printf("\tcall print_endofline\n");
	printf("\tcall menu\n");
	printf("quit:\n");
	printf("\tmov dword esp, [__esp]\n");
	printf("\tret\n");

return 0;
}